### DISCUSSION TITLE
Questions about email authorization login

### DISCUSSION THREAD

**Discussion by andyzhangwp** [QuivrHQ/quivr#2693] [Q&A]
I have two questions that I would like your help with，Thanks！

1. The email mentioned in backend/supabase/config.toml was only monitored and not actually sent. How to switch between sending genuine emails?

2. To view the monitored email details in Inbucket, how to replace 127.0.0.1 with the actual IP address and redirect to the actual URL?

Follow this link to login:
Log In ( http://127.0.0.1:54321/auth/v1/verify?token=135f146f5cfc85b1c0684172cd5dfc886620e10fd7f4530cc7685b60&type=magiclink&redirect_to=http://localhost:3000 )
Alternatively, enter the code: 038905

**Comment by dosubot** [comment]
To address your questions:

1. **Switching from Monitoring to Sending Genuine Emails**:
   To switch from monitoring to sending genuine emails, you need to disable the Inbucket email testing server and configure the `site_url` and `additional_redirect_urls` with your actual IP address in the `backend/supabase/config.toml` file. Here is the modified configuration:

   ```toml
   # Disable the Inbucket email testing server
   [inbucket]
   enabled = false

   [auth]
   enabled = true
   # Replace 'localhost' with the actual IP address
   site_url = "http://<actual-ip-address>:3000"
   # Replace 'localhost' with the actual IP address
   additional_redirect_urls = ["http://<actual-ip-address>:3000"]
   # How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
   jwt_expiry = 3600
   # If disabled, the refresh token will never expire.
   enable_refresh_token_rotation = true
   # Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
   # Requires enable_refresh_token_rotation = true.
   refresh_token_reuse_interval = 10
   # Allow/disallow new user signups to your project.
   enable_signup = true
   # Allow/disallow testing manual linking of accounts
   enable_manual_linking = false

   [auth.email]
   # Allow/disallow new user signups via email to your project.
   enable_signup = true
   # If enabled, a user will be required to confirm any email change on both the old, and new email
   # addresses. If disabled, only the new email is required to confirm.
   double_confirm_changes = true
   # If enabled, users need to confirm their email address before signing in.
   enable_confirmations = false
   ```

   Replace `<actual-ip-address>` with your actual IP address <sup>[[1]](https://github.com/QuivrHQ/quivr/blob/main/backend/supabase/config.toml)</sup>.

2. **Replacing `127.0.0.1` with the Actual IP Address for Inbucket**:
   To view the monitored email details in Inbucket and replace `127.0.0.1` with the actual IP address, you need to update the `site_url` and `additional_redirect_urls` in the same `config.toml` file as shown above. This will redirect to the actual URL for viewing email details.

By making these changes, you will disable the Inbucket email testing server and configure the system to send genuine emails, while also updating the URLs to use the actual IP address.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by andyzhangwp** [reply]
@dosu
After modifying backend/supabase/config.toml, prepare to execute npx supabase restart and prompt the need to install supabase. Worried that the data will be reinitialized, is there any other way to restart Supabase?

**Reply by dosubot** [reply]
To restart Supabase without using `npx supabase restart` and avoid the risk of data reinitialization, you can follow these steps:

1. Navigate to the backend directory:
   ```bash
   cd backend
   ```

2. Stop the Supabase services:
   ```bash
   supabase stop
   ```

3. Start the Supabase services again:
   ```bash
   supabase start
   ```

These commands will effectively restart your Supabase services without reinitializing the data <sup>[[1]](https://github.com/QuivrHQ/quivr/blob/main/docs/configuring/supabase-setup.mdx)</sup><sup>[[2]](https://github.com/QuivrHQ/quivr/blob/main/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by andyzhangwp** [reply]
@dosu 
After disabling the Inbucket email test server, the email authentication interface reported an error of 500, indicating that sending the magic link failed. How do I configure it to send emails?

**Reply by dosubot** [reply]
To configure the system to send emails after disabling the Inbucket email test server, you need to ensure that the SMTP settings are correctly configured in the `backend/supabase/config.toml` file. Here is how you can do it:

1. **Disable the Inbucket Email Test Server**:
   ```toml
   [inbucket]
   enabled = false
   ```

2. **Configure the SMTP Settings**:
   Update the `[auth.email]` section with your actual SMTP server details:

   ```toml
   [auth.email]
   enable_signup = true
   double_confirm_changes = true
   enable_confirmations = true

   # SMTP settings for sending emails
   smtp_host = "your.smtp.host"
   smtp_port = 587
   smtp_user = "your-smtp-username"
   smtp_pass = "your-smtp-password"
   smtp_sender_name = "Your Sender Name"
   smtp_sender_email = "your-sender-email@example.com"
   ```

   Replace the placeholder values (`your.smtp.host`, `your-smtp-username`, `your-smtp-password`, `Your Sender Name`, and `your-sender-email@example.com`) with the actual details of your SMTP server and email account <sup>[[1]](https://github.com/QuivrHQ/quivr/blob/main/backend/supabase/config.toml)</sup>.

3. **Restart Supabase Services**:
   After making these changes, restart the Supabase services to apply the new configuration:

   ```bash
   cd backend
   supabase stop
   supabase start
   ```

This should configure the system to send genuine emails and resolve the 500 error when sending the magic link.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by andyzhangwp** [reply]
@dosu

After adding SMTP configuration, 

  # ../../node_modules/.bin/supabase stop
  Using workdir /usr/local/Quivr/backend
  Unknown config fields: [auth.email.smtp_host auth.email.smtp_port auth.email.smtp_user auth.email.smtp_pass auth.email.smtp_sender_name auth.email.smtp_sender_email]

**Reply by dosubot** [reply]
The error indicates that the SMTP configuration fields you added are not recognized by Supabase. The correct SMTP configuration should be set using environment variables instead of directly in the `config.toml` file.

Here is how you can set the SMTP configuration using environment variables:

1. **Remove the SMTP settings from `config.toml`**:
   ```toml
   [auth.email]
   enable_signup = true
   double_confirm_changes = true
   enable_confirmations = true
   ```

2. **Set the SMTP environment variables**:
   You need to set the following environment variables in your environment or in a `.env` file:

   ```env
   SUPABASE_SMTP_HOST=your.smtp.host
   SUPABASE_SMTP_PORT=587
   SUPABASE_SMTP_USER=your-smtp-username
   SUPABASE_SMTP_PASS=your-smtp-password
   SUPABASE_SMTP_SENDER_NAME="Your Sender Name"
   SUPABASE_SMTP_SENDER_EMAIL=your-sender-email@example.com
   ```

   Replace the placeholder values with your actual SMTP server details.

3. **Restart Supabase Services**:
   After setting the environment variables, restart the Supabase services to apply the new configuration:

   ```bash
   cd backend
   supabase stop
   supabase start
   ```

This should configure the system to send genuine emails using the SMTP settings and resolve the issue of unrecognized configuration fields.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by andyzhangwp** [reply]
@dosu

I ensure that the email configuration is valid, as the same configuration information can successfully send emails in other applications using SSL. I have tried two methods, environment variables and configuration in the. env file, and restarted Quivr and Supabase, but still cannot successfully send emails. I am not sure if Supabase used SSL to send emails, or if there are other reasons?

**Reply by dosubot** [reply]
Given that your email configuration works in other applications using SSL, the issue might be related to how Supabase handles SSL configurations for email sending. Unfortunately, the repository does not provide specific details on SSL-related configurations for Supabase email sending.

Here are a few steps to troubleshoot and ensure SSL is correctly configured:

1. **Verify SSL Configuration in SMTP Settings**:
   Ensure that your SMTP server settings explicitly specify the use of SSL. For example, if your SMTP server requires SSL, you might need to use port 465 instead of 587 and ensure the `SUPABASE_SMTP_PORT` is set correctly.

   ```env
   SUPABASE_SMTP_HOST=your.smtp.host
   SUPABASE_SMTP_PORT=465
   SUPABASE_SMTP_USER=your-smtp-username
   SUPABASE_SMTP_PASS=your-smtp-password
   SUPABASE_SMTP_SENDER_NAME="Your Sender Name"
   SUPABASE_SMTP_SENDER_EMAIL=your-sender-email@example.com
   ```

2. **Check Supabase Logs for Errors**:
   Review the Supabase logs for any error messages related to email sending. This can provide more insight into what might be going wrong. You can access the logs by running:

   ```bash
   supabase logs
   ```

3. **Ensure Environment Variables are Loaded**:
   Double-check that the environment variables are correctly loaded by Supabase. You can print the environment variables to verify they are set correctly:

   ```bash
   printenv | grep SUPABASE_SMTP
   ```

4. **Use Inbucket for Debugging**:
   Temporarily re-enable Inbucket to capture and debug the email sending process. This can help you identify if the issue is with the email configuration or something else.

   ```toml
   [inbucket]
   enabled = true
   ```

5. **Supabase Configuration**:
   Ensure that the Supabase configuration is correctly set to use the provided SMTP settings. If there are any specific flags or settings required for SSL, they should be documented in the Supabase documentation.

If these steps do not resolve the issue, it might be necessary to consult the Supabase documentation or support for more detailed guidance on SSL configurations for email sending.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
